baseURL = "https://ErinOrstrom.com/"
languageCode = "en-us"
title = "Erin Orstrom"
theme = "personal-web"
copyright="Sidebar photo by Sacha Styles on Unsplash. Website Â© Erin Orstrom, {year}."
googleAnalytics = "UA-81706954-1"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Erin! :wave:"
  sub = "Technology Professional ğŸ‘©ğŸ¼â€ğŸ’». Product Owner ğŸ“. Software Developer ğŸ’». Traveler âœˆï¸. Video Gamer ğŸ®. Avid Reader ğŸ“–. Life-long Learner ğŸ’¡."

[taxonomies]
  design = "designs"
  tech = "techs"
  work = "work"

[blackfriday]
  hrefTargetBlank = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed below 404

  custom_css               = ["css/form.css", "css/custom.css"]

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "img/2016_05_19_NSS_Cohort_12_0274_T_cropped_246x246.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = "img/ErinOrstrom_favicon.png"
  customCSS = ""

[params.social]
  # codepen = "https://codepen.io/"
  # facebook = "https://www.facebook.com/" 
  github = "https://github.com/eorstrom"
  # gitlab = "https://gitlab.com/"
  instagram = "https://www.instagram.com/eeyorestrom"
  # keybase = "https://keybase.io/"
  linkedin = "https://www.linkedin.com/in/erinorstrom"
  # medium = "https://medium.com/"
  twitter = "https://twitter.com/eeyorestrom"
  # youtube = "https://www.youtube.com/"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "Home page"
  url = "/"
  weight = -140

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -130

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -120

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog section"
  url = "/post/"
  weight = -110

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact section"
  url = "/contact/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false